apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: fulfillment
  namespace: fulfillment-aap
spec:
  image_pull_policy: IfNotPresent
  controller:
    disabled: false
    task_replicas: 3
  eda:
    disabled: false
  hub:
    disabled: true
  lightspeed:
    disabled: true
