apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/core/namespaces/open-cluster-management-observability
  - ../../../base/core/configmaps/thanos-ruler-custom-rules/
  - ../../../base/core/configmaps/observability-metrics-custom-allowlist/
  - ../../../base/observability.open-cluster-management.io/multiclusterobservabilities/observability
