apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ansibleautomationplatform.yaml
- role-create-controller-token.yaml
- rolebinding-aap-fulfillment-template-publisher.yaml
- serviceaccount-template-publisher.yaml
- externalsecret-cloudkit-aap-cluster-fulfillment-ig.yaml
- externalsecret-cloudkit-aap-config-as-code-ig.yaml
